# Generated by Django 4.1 on 2023-08-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='embeddings_file',
            new_name='embeddings',
        ),
        migrations.RemoveField(
            model_name='document',
            name='text_file',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='expert',
            name='role',
            field=models.TextField(default='prominent tulku (reincarnate lama) in the Kagyu school of Tibetan Buddhism.'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='name',
            field=models.CharField(default='Thrangu Rinpoche', max_length=255),
        ),
    ]
