# Generated by Django 4.1 on 2023-08-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0002_rename_embeddings_file_document_embeddings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='html_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(default='gpt-3.5-turbo', max_length=255),
        ),
    ]
