# Generated by Django 4.1 on 2023-08-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0004_conversation_created_at_conversation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
