# django_ci.yml

name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SECURE_SSL_REDIRECT: ${{ secrets.SECURE_SSL_REDIRECT }}
      SESSION_COOKIE_SECURE: ${{ secrets.SESSION_COOKIE_SECURE }}
      CSRF_COOKIE_SECURE: ${{ secrets.CSRF_COOKIE_SECURE }}
      SECURE_BROWSER_XSS_FILTER: ${{ secrets.SECURE_BROWSER_XSS_FILTER }}
      SECURE_CONTENT_TYPE_NOSNIFF: ${{ secrets.SECURE_CONTENT_TYPE_NOSNIFF }}
      SECURE_HSTS_SECONDS: ${{ secrets.SECURE_HSTS_SECONDS }}
      SECURE_HSTS_INCLUDE_SUBDOMAINS: ${{ secrets.SECURE_HSTS_INCLUDE_SUBDOMAINS }}
      SECURE_HSTS_PRELOAD: ${{ secrets.SECURE_HSTS_PRELOAD }}
      SECURE_REFERRER_POLICY: ${{ secrets.SECURE_REFERRER_POLICY }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run Tests
        run: |
          pytest
